name: firebase_wael_abo_kalam
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  jiffy: ^4.0.0
  image_picker: ^0.7.2
  http: ^0.13.0
  shared_preferences: ^2.0.3
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.1
  cloud_firestore: ^3.2.1
  firebase_messaging: ^11.4.4
  firebase_auth: ^3.4.1
  awesome_dialog: ^2.2.1
  dropdown_search: ^0.4.8
  google_sign_in: ^5.4.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.3 
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
